#!/usr/bin/env bash
#
# Creates self-contained binaries for
# Linux, macOS and Windows using warp4j
#

# repository directory
REPO="$(cd "$(dirname "$0")" ; pwd -P)"
# fatjar subdirectory
FAT=fatjar
# warped subdirectory
WARPED=warped
# app name
APP=sm2csv

# check if warp4j installed
if ! command -v warp4j &> /dev/null ; then
    echo "Please install warp4j jar wrapper" >&2
    echo "https://github.com/guziks/warp4j" >&2
    exit 1
fi

# warping
warp4j $REPO/$FAT/$APP.jar -o $REPO/$WARPED
